sudo: false

language: node_js

node_js:
  - "9"

cache:
  yarn: true

script:
  - make

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    branch: master

addons:
  apt:
    update: true
