language: node_js

node_js:
  - 14

cache:
  yarn: true

before_install:
  - yarn global add semantic-release @semantic-release/git

script:
  - yarn lint
  - yarn build

deploy:
  provider: script
  script: npx semantic-release
  on:
    branch: master

addons:
  apt:
    update: true
