sudo: false

language: node_js

node_js:
  - "10"

cache:
  yarn: true

before_install:
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - npx nyc report --reporter=text-lcov | npx coveralls

script:
  - make

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    branch: master

addons:
  apt:
    update: true
